{% comment %} 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "yourchart.fullname" . }}-daily
  labels:
    {{- include "yourchart.labels" . | nindent 4 }}
spec:
  schedule: "/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 300 # Remove pods após 5 min
      template:
        metadata:
          labels:
            {{- include "yourchart.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["sh", "-c", "echo 'Executando job diário...' && python3 /app/active.py"]
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: kmind-client-params
          imagePullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 12 }} 
{% endcomment %}
