apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kmind-client.fullname" . }}
  labels:
    {{- include "kmind-client.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kmind-client.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python3", "/app/active.py"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: kmind-client-params
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}